### ISSUE TITLE
변수 이름 문법상 오류

### ISSUE THREAD

**Issue by potados99** [WBPBP/preshoes-shoes#2]
https://github.com/WBPBP/preshoes-shoes/blob/43f33ab06616601a11adbe9bbe8d978f1d070cfd/preshoes-shoes_final.ino#L9

`datum`의 복수형이 `data`입니다.

이와 별개로, 실제로는 입력 데이터를 저장할 배열은 필요하지 않습니다.

`int input` 전역변수 하나만 사용하는 방법으로 코드를 개선해 보세요.

**Comment by dobbi030** [comment]
아아 네 data가 복수형인거는 알았는데 data를 변수 명으로 할 수 가 없더라고영 이미 기능이 지정된 변수인것같아요.

코드 개선안은 datas배열 대신 int input을 사용하라는 말씀이신거죠?

**Comment by potados99** [comment]
> data를 변수 명으로 할 수 가 없더라고영 이미 기능이 지정된 변수인것같아요.

그거 몰랐네요 감사합니다

> 코드 개선안은 datas배열 대신 int input을 사용하라는 말씀이신거죠?

예.

새로운 제안도 있으니 이 부분은 아래 이슈 참고 부탁드립니다.

#4
