### ISSUE TITLE
나눗셈 연산자 대신 쉬프트 연산자

### ISSUE THREAD

**Issue by potados99** [WBPBP/preshoes-shoes#3]
https://github.com/WBPBP/preshoes-shoes/blob/43f33ab06616601a11adbe9bbe8d978f1d070cfd/preshoes-shoes_final.ino#L20

어셈블리를 분석해보지는 않아서 확실하지 않지만, 2의 제곱수로 나누는 것이라면 쉬프트 연산을 사용하는 것이 성능상 유리할 것으로 보입니다.

**Comment by dobbi030** [comment]
아아 네 그러면 >>5 하면 되겠네요!
& 0xF를 해줘야 할까요?

**Comment by dobbi030** [comment]
아 5가 아니라 8이네요!

**Comment by potados99** [comment]
> 아아 네 그러면 >>5 하면 되겠네요!
> & 0xF를 해줘야 할까요?

`& 0xF`는 필요 없어 보입니다.
