### ISSUE TITLE
기기 하나가 센서값이 이상하게 들어옵니다.

### ISSUE THREAD

**Issue by dobbi030** [WBPBP/preshoes-shoes#5]
전류량 측정하는 기기로 센서의 작동을 검사해 본 결과 한 기기의 센서 전체가 센서의 눌림에 상관없이 높은 값이 들어오는 것으로 측정됩니다.

이때 해볼 수 있는 방법은 두가지 입니다.
1. 해당 오류가 발생할 수 있는 지점을 다시 만들면서 오류 발생 지점을 확인한다.
2. 새로운 기기를 제작한다.

현재로서는 수요일까지 1번을 시도하되 1번을 통해 해결되지 않는다면 그 즉시 2번으로 진행해보는 방법을 선택하려 합니다.

좀 더 좋은 방안 있으시면 조언 부탁드립니다.

**Comment by potados99** [comment]
새로 만드세요. 아래 부품을 사용하세요.

- 아날로그 16채널 멀티플렉서
- 10k옴 저항 array
- FSR 센서 완제품

재료비 신청은 29일까지입니다.
