### ISSUE TITLE
센서가 서로에게 영향을 주고받습니다.

### ISSUE THREAD

**Issue by dobbi030** [WBPBP/preshoes-shoes#6]
센서 값이 서로의 영향을 받아 한꺼번에 올라가고 한꺼번에 내려갑니다.

제가 생각한 원인은 12개가 같은 GND와 전원 선을 공유하고 있다는 것입니다.

따라서 12개의 디지털 핀을 이용하여 각각에 전원을 주면 서로에게 영향을 받지 않을 것으로 예상됩니다.

**Comment by potados99** [comment]
pull-down 저항을 작은 것을 써서 그렇습니다. 10kOhm을 사용하거나 다이오드를 붙여야 하겠습니다...

**Comment by dobbi030** [comment]
해결되었습니다. 굉장히 어이없게도 만들어 놓은 신발에 vcc와 GND를 연결하지 않았습니다.

**Comment by potados99** [comment]
다행입니다
