### ISSUE TITLE
M 점퍼 케이블과 연결한 부분이 취약합니다.

### ISSUE THREAD

**Issue by dobbi030** [WBPBP/preshoes-shoes#7]
점퍼 케이블과 연결한 부분이 물리적으로 취약합니다.

따라서 재히의 의견대로 보드쪽 점퍼 케이블 길이는 늘리고 깔창쪽 점퍼 케이블 길이는 줄여 신발에 붙일 수 있게 만들어 보겠습니다.

**Comment by potados99** [comment]
하드웨어 구성을 자세하게 알려주실 수 있나요? M 점퍼 케이블이 어떤 부분에 사용되는지 궁금합니다

**Comment by dobbi030** [comment]
아 제 착오가 있었네요 F 점퍼 케이블입니다.
