### ISSUE TITLE
센서 좌표

### ISSUE THREAD

**Issue by potados99** [WBPBP/preshoes-shoes#8]
센서 12개 좌표 업로드해주세요.

본인 발 사이즈 기준, 단위는 mm 사용해주세요.

**Comment by dobbi030** [comment]
저번에 사진 올려드린거 참고해주세요. 상세 설명도 써놓았습니다.

**Comment by potados99** [comment]
네 그거 여기에 올려주세요. 여기에 없으면 없는거예요.

**Comment by potados99** [comment]
올렸습니다.
