### ISSUE TITLE
새 프로토콜

### ISSUE THREAD

**Issue by potados99** [WBPBP/preshoes-shoes#9]
배터리 상태도 보여줄 수 있는 프로토콜을 만들어 봅시다.

일단 페이로드의 모든 바이트가 240(`0xF0`) 미만의 값을 가지도록 합시다. 안 그러면 delimiter를 구분할 수가 없어요 ㅠ

상위 4비트가 1인, 즉 `0XF0` 이상인 바이트는 패킷의 시작으로 간주합니다.

시작 바이트는 패킷의 시작을 알리는 역할 뿐만 아니라 패킷의 종류를 알리는 역할도 합니다. 

시작 바이트의 하위 4비트가 나타내는 값이 1이면 뒤에 샘플 데이터 12바이트가, 2이면 배터리 잔량 1바이트가 이어질 것을 뜻합니다.

보내는 쪽에서는 첫 바이트에 `0xF1` 또는 `0xF2`를, 그 다음 바이트부터는 패킷 종류에 맞는 데이터를 보내면 됩니다.

받는 쪽에서는 상위 4비트가 모두 1인 바이트를 기다리다가, 시작 바이트가 도착하면 패킷 종류에 따라 페이로드를 적절한 수(배터리라면 1바이트, 샘플 테이터라면 12바이트) 만큼 읽으면 됩니다.

어때요?

**Comment by potados99** [comment]
천잰데요? 좋아요

**Comment by dobbi030** [comment]
좋은생각입니다. 기능이 점점 풍성해지네요

**Comment by hseol** [comment]
ㅋㅋㅋㅋ 본인이 대답하지말라고요 ㅠㅠㅋㅋㅋㅋㅋ 배터리 잔량 표시가 성공적이면 훨씬 퀄리티 있어보일 것 같습니다 ㅋㅋㅋ

**Comment by potados99** [comment]
ㅠㅠㅠ..답변 감사합니다ㅜ 감동..ㅠ

**Comment by potados99** [comment]
구현 끝!
